# .github/workflows/cici.yml

name: CICI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CCACHE_DIR: /ws/ccache
  MAKEFLAGS: -j2

jobs:
  cogutil:
    name: CogUtil Job
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
      env:
        CCACHE_DIR: /ws/ccache

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start restoring ccache
        run: date +%d-%m-%Y > /tmp/date

      - name: Restore ccache
        uses: actions/cache@v4
        with:
          path: /ws/ccache
          key: ccache-${{ hashFiles('/tmp/date') }}
          restore-keys: |
            ccache-

      - name: Set number of make jobs
        run: echo "MAKEFLAGS=-j2" >> $GITHUB_ENV

      - name: CMake Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Build tests
        run: |
          cd build
          make tests

      - name: Run tests
        run: |
          cd build
          make check ARGS="$MAKEFLAGS"

      - name: Print test log
        if: always()
        run: |
          cat build/tests/Testing/Temporary/LastTest.log || echo "Test log not found."

      - name: Upload cogutil artifact
        uses: actions/upload-artifact@v4
        with:
          name: cogutil
          path: /ws/cogutil

      - name: Upload ccache artifact
        uses: actions/upload-artifact@v4
        with:
          name: ccache
          path: /ws/ccache

  atomspace:
    name: AtomSpace Job
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
      env:
        PGHOST: opencog-postgres
        PGUSER: opencog_test
        PGPASSWORD: cheese
        CCACHE_DIR: /ws/ccache

    services:
      opencog-postgres:
        image: opencog/postgres
        env:
          POSTGRES_USER: opencog_test
          POSTGRES_PASSWORD: cheese
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    needs: cogutil

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start restoring ccache
        run: date +%d-%m-%Y > /tmp/date

      - name: Restore ccache
        uses: actions/cache@v4
        with:
          path: /ws/ccache
          key: ccache-${{ hashFiles('/tmp/date') }}
          restore-keys: |
            ccache-

      - name: Set number of make jobs
        run: echo "MAKEFLAGS=-j2" >> $GITHUB_ENV

      - name: CMake Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Build tests
        run: |
          cd build
          make tests

      - name: Run tests
        run: |
          cd build
          make check ARGS="$MAKEFLAGS"

      - name: Print test log
        if: always()
        run: |
          cat build/tests/Testing/Temporary/LastTest.log || echo "Test log not found."

      - name: Upload atomspace artifact
        uses: actions/upload-artifact@v4
        with:
          name: atomspace
          path: /ws/atomspace

      - name: Upload ccache artifact
        uses: actions/upload-artifact@v4
        with:
          name: ccache
          path: /ws/ccache

  cogserver:
    name: CogServer Job
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
      env:
        CCACHE_DIR: /ws/ccache

    needs: atomspace

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download atomspace artifact
        uses: actions/download-artifact@v4
        with:
          name: atomspace
          path: /ws/atomspace

      - name: Download cogutil artifact
        uses: actions/download-artifact@v4
        with:
          name: cogutil
          path: /ws/cogutil

      - name: Download ccache artifact
        uses: actions/download-artifact@v4
        with:
          name: ccache
          path: /ws/ccache

      - name: Set number of make jobs
        run: echo "MAKEFLAGS=-j2" >> $GITHUB_ENV

      - name: CMake Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Build tests
        run: |
          cd build
          make tests

      - name: Run tests
        run: |
          cd build
          make check ARGS="$MAKEFLAGS"

      - name: Print test log
        if: always()
        run: |
          cat build/tests/Testing/Temporary/LastTest.log || echo "Test log not found."

      - name: Upload cogserver artifact
        uses: actions/upload-artifact@v4
        with:
          name: cogserver
          path: /ws/cogserver

      - name: Upload ccache artifact
        uses: actions/upload-artifact@v4
        with:
          name: ccache
          path: /ws/ccache

  attention:
    name: Attention Job
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
      env:
        CCACHE_DIR: /ws/ccache

    needs: cogserver

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download cogserver artifact
        uses: actions/download-artifact@v4
        with:
          name: cogserver
          path: /ws/cogserver

      - name: Download atomspace artifact
        uses: actions/download-artifact@v4
        with:
          name: atomspace
          path: /ws/atomspace

      - name: Download cogutil artifact
        uses: actions/download-artifact@v4
        with:
          name: cogutil
          path: /ws/cogutil

      - name: Download ccache artifact
        uses: actions/download-artifact@v4
        with:
          name: ccache
          path: /ws/ccache

      - name: Set number of make jobs
        run: echo "MAKEFLAGS=-j2" >> $GITHUB_ENV

      - name: CMake Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Build tests
        run: |
          cd build
          make tests

      - name: Run tests
        run: |
          cd build
          make check ARGS="$MAKEFLAGS"

      - name: Print test log
        if: always()
        run: |
          cat build/tests/Testing/Temporary/LastTest.log || echo "Test log not found."

      - name: Upload attention artifact
        uses: actions/upload-artifact@v4
        with:
          name: attention
          path: /ws/attention

      - name: Upload ccache artifact
        uses: actions/upload-artifact@v4
        with:
          name: ccache
          path: /ws/ccache

  unify:
    name: Unify Job
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
      env:
        CCACHE_DIR: /ws/ccache

    needs: atomspace

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download atomspace artifact
        uses: actions/download-artifact@v4
        with:
          name: atomspace
          path: /ws/atomspace

      - name: Download cogutil artifact
        uses: actions/download-artifact@v4
        with:
          name: cogutil
          path: /ws/cogutil

      - name: Download ccache artifact
        uses: actions/download-artifact@v4
        with:
          name: ccache
          path: /ws/ccache

      - name: Set number of make jobs
        run: echo "MAKEFLAGS=-j2" >> $GITHUB_ENV

      - name: CMake Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Build tests
        run: |
          cd build
          make tests

      - name: Run tests
        run: |
          cd build
          make check ARGS="$MAKEFLAGS"

      - name: Print test log
        if: always()
        run: |
          cat build/tests/Testing/Temporary/LastTest.log || echo "Test log not found."

      - name: Upload unify artifact
        uses: actions/upload-artifact@v4
        with:
          name: unify
          path: /ws/unify

      - name: Upload ccache artifact
        uses: actions/upload-artifact@v4
        with:
          name: ccache
          path: /ws/ccache

  ure:
    name: URE Job
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
      env:
        CCACHE_DIR: /ws/ccache

    needs:
      - atomspace
      - unify

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download unify artifact
        uses: actions/download-artifact@v4
        with:
          name: unify
          path: /ws/unify

      - name: Download atomspace artifact
        uses: actions/download-artifact@v4
        with:
          name: atomspace
          path: /ws/atomspace

      - name: Download cogutil artifact
        uses: actions/download-artifact@v4
        with:
          name: cogutil
          path: /ws/cogutil

      - name: Download ccache artifact
        uses: actions/download-artifact@v4
        with:
          name: ccache
          path: /ws/ccache

      - name: Set number of make jobs
        run: echo "MAKEFLAGS=-j2" >> $GITHUB_ENV

      - name: CMake Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Build tests
        run: |
          cd build
          make tests

      - name: Run tests
        run: |
          cd build
          make check ARGS="$MAKEFLAGS"

      - name: Install URE
        run: |
          cd build
          make install
          sudo ldconfig

      - name: Print test log
        if: always()
        run: |
          cat build/tests/Testing/Temporary/LastTest.log || echo "Test log not found."

      - name: Upload ure artifact
        uses: actions/upload-artifact@v4
        with:
          name: ure
          path: /ws/ure

      - name: Upload ccache artifact
        uses: actions/upload-artifact@v4
        with:
          name: ccache
          path: /ws/ccache

  miner:
    name: Miner Job
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
      env:
        CCACHE_DIR: /ws/ccache

    needs: ure

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download ure artifact
        uses: actions/download-artifact@v4
        with:
          name: ure
          path: /ws/ure

      - name: Download atomspace artifact
        uses: actions/download-artifact@v4
        with:
          name: atomspace
          path: /ws/atomspace

      - name: Download cogutil artifact
        uses: actions/download-artifact@v4
        with:
          name: cogutil
          path: /ws/cogutil

      - name: Download ccache artifact
        uses: actions/download-artifact@v4
        with:
          name: ccache
          path: /ws/ccache

      - name: Set number of make jobs
        run: echo "MAKEFLAGS=-j2" >> $GITHUB_ENV

      - name: CMake Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Build tests
        run: |
          cd build
          make tests

      - name: Run tests
        run: |
          cd build
          make check ARGS="$MAKEFLAGS"

      - name: Install Miner
        run: |
          cd build
          make install
          sudo ldconfig

      - name: Print test log
        if: always()
        run: |
          cat build/tests/Testing/Temporary/LastTest.log || echo "Test log not found."

      - name: Upload miner artifact
        uses: actions/upload-artifact@v4
        with:
          name: miner
          path: /ws/miner

      - name: Upload ccache artifact
        uses: actions/upload-artifact@v4
        with:
          name: ccache
          path: /ws/ccache

  asmoses:
    name: ASMoses Job
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
      env:
        CCACHE_DIR: /ws/ccache

    needs: miner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download miner artifact
        uses: actions/download-artifact@v4
        with:
          name: miner
          path: /ws/miner

      - name: Download ure artifact
        uses: actions/download-artifact@v4
        with:
          name: ure
          path: /ws/ure

      - name: Download atomspace artifact
        uses: actions/download-artifact@v4
        with:
          name: atomspace
          path: /ws/atomspace

      - name: Download cogutil artifact
        uses: actions/download-artifact@v4
        with:
          name: cogutil
          path: /ws/cogutil

      - name: Download ccache artifact
        uses: actions/download-artifact@v4
        with:
          name: ccache
          path: /ws/ccache

      - name: Set number of make jobs
        run: echo "MAKEFLAGS=-j2" >> $GITHUB_ENV

      - name: CMake Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Build tests
        run: |
          cd build
          make tests

      - name: Run tests
        run: |
          cd build
          make check ARGS="$MAKEFLAGS"

      - name: Install ASMoses
        run: |
          cd build
          make install
          sudo ldconfig

      - name: Print test log
        if: always()
        run: |
          cat build/tests/Testing/Temporary/LastTest.log || echo "Test log not found."

      - name: Upload asmoses artifact
        uses: actions/upload-artifact@v4
        with:
          name: asmoses
          path: /ws/asmoses

      - name: Upload ccache artifact
        uses: actions/upload-artifact@v4
        with:
          name: ccache
          path: /ws/ccache

  opencog:
    name: OpenCog Job
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
      env:
        CCACHE_DIR: /ws/ccache

    needs: asmoses

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download asmoses artifact
        uses: actions/download-artifact@v4
        with:
          name: asmoses
          path: /ws/asmoses

      - name: Download miner artifact
        uses: actions/download-artifact@v4
        with:
          name: miner
          path: /ws/miner

      - name: Download ure artifact
        uses: actions/download-artifact@v4
        with:
          name: ure
          path: /ws/ure

      - name: Download atomspace artifact
        uses: actions/download-artifact@v4
        with:
          name: atomspace
          path: /ws/atomspace

      - name: Download cogutil artifact
        uses: actions/download-artifact@v4
        with:
          name: cogutil
          path: /ws/cogutil

      - name: Download ccache artifact
        uses: actions/download-artifact@v4
        with:
          name: ccache
          path: /ws/ccache

      - name: Set number of make jobs
        run: echo "MAKEFLAGS=-j2" >> $GITHUB_ENV

      - name: Install Link Grammar Atomese
        run: |
          git clone --depth 1 https://github.com/opencog/lg-atomese /ws/lg-atomese
          mkdir -p /ws/lg-atomese/build
          cd /ws/lg-atomese/build
          cmake ..
          make -j2
          make install
          sudo ldconfig

      - name: Clone OpenCog Repository
        run: git clone --depth 1 https://github.com/opencog/opencog.git /ws/opencog

      - name: CMake Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build OpenCog
        run: |
          cd build
          make

      - name: Build tests
        run: |
          cd build
          make tests

      - name: Run tests
        run: |
          cd build
          make check ARGS="$MAKEFLAGS"

      - name: Install OpenCog
        run: |
          cd build
          make install
          sudo ldconfig

      - name: Print test log
        if: always()
        run: |
          cat build/tests/Testing/Temporary/LastTest.log || echo "Test log not found."

      - name: Upload opencog artifact
        uses: actions/upload-artifact@v4
        with:
          name: opencog
          path: /ws/opencog

      - name: Upload ccache artifact
        uses: actions/upload-artifact@v4
        with:
          name: ccache
          path: /ws/ccache

  package:
    name: Package Job
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
    env:
      CCACHE_DIR: /ws/ccache

    needs: opencog
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download opencog artifact
        uses: actions/download-artifact@v4
        with:
          name: opencog
          path: /ws/opencog

      - name: Download ccache artifact
        uses: actions/download-artifact@v4
        with:
          name: ccache
          path: /ws/ccache

      - name: Build Debian package
        run: |
          cd /ws/opencog/build
          make install
          make package || echo "Package target not defined."

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages
          path: /ws/opencog/build/packages/ || echo "No packages to upload."

      - name: Save ccache
        uses: actions/cache@v4
        with:
          path: /ws/ccache
          key: ccache-${{ hashFiles('/tmp/date') }}
          restore-keys: |
            ccache-
